### ISSUE TITLE
ncnn Models

### ISSUE THREAD

**Issue by stackByStack** [twlelev/Yolov9-Ncnn#2]
I would quite appreciate it if you could release `yolov9-c-converted-sim.param` and `yolov9-c-converted-sim.bin`.

As now, it couldn't detect anything with my own generated weights files, which followed the export instructions of official yolov9 repo and ncnn export tools. 

I am desperate for weights files mentioned above, as they are the final clues to solve the problem.

Thanks so much for your help!

**Comment by twlelev** [comment]
i'm sorry. I have already uploaded the model. Later on, I will provide instructions on how to convert it to a model supported by ncnn.

**Comment by Qengineering** [comment]
Could you also provide the `yolov9-c-converted-sim.param`?

**Comment by twlelev** [comment]
I was busy heading home and uploaded the wrong model. The previous file is not for ncnn.it's for openvino.

**Comment by stackByStack** [comment]
Thanks for your help!

It works quite well!

It would be much better if there is any instructions to generate them, as I am doing a few experiments for optimizing inference performance on Android and need to regenerate them over and over again.

Nothing could express my gratitude since I have been stuck here for more than a week🤣🤣.
